type xero_currency= {
    code: string;
    description: string;
};

const xero_currency : { [key: string]: xero_currency } = {
    "USD": { code: "USD", description: "US Dollar" },
    "CAD": { code: "CAD", description: "Canadian Dollar" },
    "EUR": { code: "EUR", description: "Euro" },
    "AED": { code: "AED", description: "Emirati Dirham" },
    "AFN": { code: "AFN", description: "Afghan Afghani" },
    "ALL": { code: "ALL", description: "Albanian Lek" },
    "AMD": { code: "AMD", description: "Armenian Dram" },
    "ARS": { code: "ARS", description: "Argentine Peso" },
    "AUD": { code: "AUD", description: "Australian Dollar" },
    "AZN": { code: "AZN", description: "Azerbaijan Manat" },
    "BAM": { code: "BAM", description: "Bosnia-Herzegovina Convertible Mark" },
    "BDT": { code: "BDT", description: "Bangladeshi Taka" },
    "BGN": { code: "BGN", description: "Bulgarian Lev" },
    "BHD": { code: "BHD", description: "Bahraini Dinar" },
    "BIF": { code: "BIF", description: "Burundian Franc" },
    "BND": { code: "BND", description: "Bruneian Dollar" },
    "BOB": { code: "BOB", description: "Bolivian Boliviano" },
    "BRL": { code: "BRL", description: "Brazilian Real" },
    "BWP": { code: "BWP", description: "Botswanan Pula" },
    "BYN": { code: "BYN", description: "Belarusian Ruble" },
    "BZD": { code: "BZD", description: "Belize Dollar" },
    "CDF": { code: "CDF", description: "Congolese Franc" },
    "CHF": { code: "CHF", description: "Swiss Franc" },
    "CLP": { code: "CLP", description: "Chilean Peso" },
    "CNY": { code: "CNY", description: "Chinese Yuan" },
    "COP": { code: "COP", description: "Colombian Peso" },
    "CRC": { code: "CRC", description: "Costa Rican Colón" },
    "CVE": { code: "CVE", description: "Cape Verdean Escudo" },
    "CZK": { code: "CZK", description: "Czech Republic Koruna" },
    "DJF": { code: "DJF", description: "Djiboutian Franc" },
    "DKK": { code: "DKK", description: "Danish Krone" },
    "DOP": { code: "DOP", description: "Dominican Peso" },
    "DZD": { code: "DZD", description: "Algerian Dinar" },
    "EEK": { code: "EEK", description: "Estonian Kroon" },
    "EGP": { code: "EGP", description: "Egyptian Pound" },
    "ERN": { code: "ERN", description: "Eritrean Nakfa" },
    "ETB": { code: "ETB", description: "Ethiopian Birr" },
    "GBP": { code: "GBP", description: "British Pound Sterling" },
    "GEL": { code: "GEL", description: "Georgian Lari" },
    "GHS": { code: "GHS", description: "Ghanaian Cedi" },
    "GNF": { code: "GNF", description: "Guinean Franc" },
    "GTQ": { code: "GTQ", description: "Guatemalan Quetzal" },
    "HKD": { code: "HKD", description: "Hong Kong Dollar" },
    "HNL": { code: "HNL", description: "Honduran Lempira" },
    "HRK": { code: "HRK", description: "Croatian Kuna" },
    "HUF": { code: "HUF", description: "Hungarian Forint" },
    "IDR": { code: "IDR", description: "Indonesian Rupiah" },
    "ILS": { code: "ILS", description: "Israeli New Sheqel" },
    "INR": { code: "INR", description: "Indian Rupee" },
    "IQD": { code: "IQD", description: "Iraqi Dinar" },
    "IRR": { code: "IRR", description: "Iranian Rial" },
    "ISK": { code: "ISK", description: "Icelandic Króna" },
    "JMD": { code: "JMD", description: "Jamaican Dollar" },
    "JOD": { code: "JOD", description: "Jordanian Dinar" },
    "JPY": { code: "JPY", description: "Japanese Yen" },
    "KES": { code: "KES", description: "Kenyan Shilling" },
    "KHR": { code: "KHR", description: "Cambodian Riel" },
    "KMF": { code: "KMF", description: "Comorian Franc" },
    "KRW": { code: "KRW", description: "South Korean Won" },
    "KWD": { code: "KWD", description: "Kuwaiti Dinar" },
    "KZT": { code: "KZT", description: "Kazakhstani Tenge" },
    "LBP": { code: "LBP", description: "Lebanese Pound" },
    "LKR": { code: "LKR", description: "Sri Lankan Rupee" },
    "LTL": { code: "LTL", description: "Lithuanian Litas" },
    "LVL": { code: "LVL", description: "Latvian Lats" },
    "LYD": { code: "LYD", description: "Libyan Dinar" },
    "MAD": { code: "MAD", description: "Moroccan Dirham" },
    "MDL": { code: "MDL", description: "Moldovan Leu" },
    "MGA": { code: "MGA", description: "Malagasy Ariary" },
    "MKD": { code: "MKD", description: "Macedonian Denar" },
    "MMK": { code: "MMK", description: "Myanma Kyat" },
    "MOP": { code: "MOP", description: "Macanese Pataca" },
    "MUR": { code: "MUR", description: "Mauritian Rupee" },
    "MXN": { code: "MXN", description: "Mexican Peso" },
    "MYR": { code: "MYR", description: "Malaysian Ringgit" },
    "MZN": { code: "MZN", description: "Mozambican Metical" },
    "NAD": { code: "NAD", description: "Namibian Dollar" },
    "NGN": { code: "NGN", description: "Nigerian Naira" },
    "NIO": { code: "NIO", description: "Nicaraguan Córdoba" },
    "NOK": { code: "NOK", description: "Norwegian Krone" },
    "NPR": { code: "NPR", description: "Nepalese Rupee" },
    "NZD": { code: "NZD", description: "New Zealand Dollar" },
    "OMR": { code: "OMR", description: "Omani Rial" },
    "PAB": { code: "PAB", description: "Panamanian Balboa" },
    "PEN": { code: "PEN", description: "Peruvian Nuevo Sol" },
    "PHP": { code: "PHP", description: "Philippine Peso" },
    "PKR": { code: "PKR", description: "Pakistani Rupee" },
    "PLN": { code: "PLN", description: "Polish Zloty" },
    "PYG": { code: "PYG", description: "Paraguayan Guarani" },
    "QAR": { code: "QAR", description: "Qatari Rial" },
    "RON": { code: "RON", description: "Romanian Leu" },
    "RSD": { code: "RSD", description: "Serbian Dinar" },
    "RUB": { code: "RUB", description: "Russian Ruble" },
    "RWF": { code: "RWF", description: "Rwandan Franc" },
    "SAR": { code: "SAR", description: "Saudi Riyal" },
    "SDG": { code: "SDG", description: "Sudanese Pound" },
    "SEK": { code: "SEK", description: "Swedish Krona" },
    "SGD": { code: "SGD", description: "Singapore Dollar" },
    "SOS": { code: "SOS", description: "Somali Shilling" },
    "SYP": { code: "SYP", description: "Syrian Pound" },
    "THB": { code: "THB", description: "Thai Baht" },
    "TND": { code: "TND", description: "Tunisian Dinar" },
    "TOP": { code: "TOP", description: "Tongan Paʻanga" },
    "TRY": { code: "TRY", description: "Turkish Lira" },
    "TTD": { code: "TTD", description: "Trinidad and Tobago Dollar" },
    "TWD": { code: "TWD", description: "New Taiwan Dollar" },
    "TZS": { code: "TZS", description: "Tanzanian Shilling" },
    "UAH": { code: "UAH", description: "Ukrainian Hryvnia" },
    "UGX": { code: "UGX", description: "Ugandan Shilling" },
    "UYU": { code: "UYU", description: "Uruguayan Peso" },
    "UZS": { code: "UZS", description: "Uzbekistan Som" },
    "VEF": { code: "VEF", description: "Venezuelan Bolívar" },
    "VND": { code: "VND", description: "Vietnamese Dong" },
    "ZAR": { code: "ZAR", description: "South African Rand" }
};

export default xero_currency;
